#ifndef A2_SIMPLENAVIGATOR_V1_0_0_S21_GRAPH_ALGORITHMS_H
#define A2_SIMPLENAVIGATOR_V1_0_0_S21_GRAPH_ALGORITHMS_H

class GraphAlgorithmss {

};


#endif //A2_SIMPLENAVIGATOR_V1_0_0_S21_GRAPH_ALGORITHMS_H
